version: "${COMPOSE_VERSION}"
services:
  web:
    build: .
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: ${FLASK_ENV}
  redis:
    image: "redis:alpine"